### PR TITLE
Bugfix: Correctly escape regex values when big image

### PR DESCRIPTION
**Pull request by ceesvanegmond**
We had some issues with some of the base64 encodings. This regex fix fixes this by correctly escaping the right values.

### CODE REVIEW

**Comment by J-Ben87** [comment]
Hi,

I don't understand your changes. Why adding a `?` after a `.*` ? Why escaping characters that don't require to be escaped?

Plus the tests are failing. Could you please check why and fix it?

**Comment by J-Ben87** [comment]
Well it seems that travis failing is due to an issue on their side.

**Comment by ceesvanegmond** [comment]
Hmmm can't reproduce this issue anymore. Let's close it for now.

**Comment by ceesvanegmond** [comment]
@J-Ben87 Ah, I can reproduce it again, when I upload this image (https://gist.github.com/ceesvanegmond/f8409b2d1584f5f764e0287c12ca2f0d).

`null` is produced by the original piece of code which is:
```php
$base64 = preg_replace('/data:.*;base64,/', '', $value['base64']);
```

This doesn't match, although it's a valid image.

Works with the fix I pushed earlier:

```php
$base64 = preg_replace('/data\:.*?base64\,/', '', $value['base64']);
```

**Comment by J-Ben87** [comment]
Hmm strange behaviour from the regex indeed...
Instead of using a regex, I suggest we implement the following:

```php
$prefixLenght = strpos($value['base64'], 'base64,') + 7;
$base64 = substr($value['base64'], $prefixLength);
```

Could you please update your pull request accordingly?

**Comment by ceesvanegmond** [comment]
@J-Ben87 See #36

**Pull request closed without merging**
