### PR TITLE
Feature: Add nl language to the project

### PR DESCRIPTION
**Pull request by ceesvanegmond**
Add Dutch locale to the project

### CODE REVIEW

**Comment by J-Ben87** [comment]
Hi,

I don't understand your pull request: your translation file only contains english translations. Did you forget something?

Plus the tests are failing. Could you please check why and fix it?

**Comment by ceesvanegmond** [comment]
@J-Ben87 Ah excuse me, I probably commited the wrong file. Here you go.

**Comment by ceesvanegmond** [comment]
@J-Ben87 I don't know why the build is failing. Looks like PHPCS error. Wrong exit code. When i test the command on OSX, exit code is zero, so I really don't know how to fix the build.

**Comment by J-Ben87** [comment]
Thanks for trying, I'll give it a look ;)

**Comment by J-Ben87** [comment]
Well it seems that travis failing is due to an issue on their side. I'll accept your PR.

**Comment by ceesvanegmond** [comment]
Thanks. Would be awesome if it could be tagged :-)

**Comment by ceesvanegmond** [comment]
What about 1.7.1?

**Comment by J-Ben87** [comment]
Done: https://packagist.org/packages/presta/image-bundle#v1.7.1

Sorry for the delay, I was a bit busy lately ;)

**Pull request merged**
