### PR TITLE
Testme

### PR DESCRIPTION
**Pull request by ahazebroucq**

### CODE REVIEW

**Comment by ahazebroucq** [comment]
Woops that was en error, sorry :/

**Comment by J-Ben87** [comment]
I reopened your PR since you told me you closed it by mistake, but I can't merge it because the tests are failing

**Comment by ahazebroucq** [comment]
Well, the PR itself was an error actually, I wanted to open a PR in my own fork and not your original bundle. It was a work in progress and I just wanted to launch the test suite with Travis.
The tests fail because it tests the bundle with some impossible PHP/Symfony combination, like SF4 and PHP 5.
But nevermind, you can close this PR, as the bundle require more work to be fully SF4-compatible.

**Comment by J-Ben87** [comment]
Ok sorry, I misunderstood ;)

**Pull request closed without merging**
